# Generated by Django 5.1.5 on 2026-08-10 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('tenants', '0003_client_brand_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformidentity',
            name='last_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.client', verbose_name='last institution used'),
        ),
    ]
