# Generated by Django 5.1.5 on 2026-08-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Set when the person signs in with a platform-wide credential.', null=True, verbose_name='platform identity'),
        ),
    ]
