# Generated by Django 5.1.5 on 2026-07-27 01:35

import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='legal name')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='tax ID')),
                ('default_language', models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=5, verbose_name='default language')),
                ('timezone', models.CharField(default='UTC', max_length=64, verbose_name='timezone')),
                ('on_trial', models.BooleanField(default=True, verbose_name='on trial')),
                ('paid_until', models.DateField(blank=True, null=True, verbose_name='paid until')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'institution',
                'verbose_name_plural': 'institutions',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.client')),
            ],
            options={
                'verbose_name': 'domain',
                'verbose_name_plural': 'domains',
            },
        ),
    ]
