# Generated by Django 5.1.5 on 2026-08-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='default_currency',
            field=models.CharField(choices=[('MXN', 'Mexican peso'), ('USD', 'US dollar')], default='MXN', help_text='Currency used for every invoice issued by this institution.', max_length=3, verbose_name='default currency'),
        ),
    ]
