# Generated by Django 5.1.5 on 2026-08-10 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_client_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='brand_color',
            field=models.CharField(default='#1d4ed8', help_text='Six-digit hex. The rest of the palette is derived from it.', max_length=7, validators=[django.core.validators.RegexValidator(message='Use a six-digit hex colour, e.g. #1d4ed8.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='brand colour'),
        ),
    ]
