# Generated by Django 5.1.5 on 2026-08-11 23:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_client_disabled_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='disabled_modules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('users', 'Users'), ('academic', 'Academic'), ('subjects', 'Subjects'), ('grades', 'Gradebook'), ('billing', 'Billing'), ('schedule', 'Schedule'), ('attendance', 'Attendance')], max_length=32), blank=True, default=list, help_text='Modules switched off for this institution. Empty means all are on.', size=None, verbose_name='disabled modules'),
        ),
    ]
