# Generated by Django 5.1.5 on 2026-08-11 16:11

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('ordinal', models.PositiveSmallIntegerField(default=1, help_text='Order within the year. Report cards are printed in this order.', verbose_name='position')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('is_current', models.BooleanField(db_index=True, default=False, help_text='The period the gradebook opens on.', verbose_name='current')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='academic.academicyear', verbose_name='academic year')),
            ],
            options={
                'verbose_name': 'evaluation period',
                'verbose_name_plural': 'evaluation periods',
                'ordering': ('academic_year__start_date', 'ordinal'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='maximum score')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Relative to the other assessments in the same period.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='weight')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academic.subject', verbose_name='subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academic.term', verbose_name='evaluation period')),
            ],
            options={
                'verbose_name': 'assessment',
                'verbose_name_plural': 'assessments',
                'ordering': ('term__ordinal', 'due_date', 'name'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='score')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='comment')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academic.assessment', verbose_name='assessment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academic.enrollment', verbose_name='enrollment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_grades', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grades',
                'ordering': ('assessment__term__ordinal', 'assessment__name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('assessment', 'enrollment'), name='grade_unique_per_assessment_and_enrollment')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('academic_year', 'ordinal'), name='term_unique_ordinal_per_year'),
        ),
    ]
