# Generated by Django 5.1.5 on 2026-08-11 23:00

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_term_assessment_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('room', models.CharField(blank=True, help_text='Where the group is by default. A timetable entry may override it.', max_length=64, verbose_name='home room')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='academic.academicyear', verbose_name='academic year')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='academic.program', verbose_name='programme')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutored_groups', to=settings.AUTH_USER_MODEL, verbose_name='tutor')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'ordering': ('academic_year__start_date', 'program__code', 'name'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academic.studentgroup', verbose_name='group'),
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], db_index=True, verbose_name='weekday')),
                ('start_time', models.TimeField(verbose_name='starts at')),
                ('end_time', models.TimeField(verbose_name='ends at')),
                ('room', models.CharField(blank=True, max_length=64, verbose_name='room')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='academic.studentgroup', verbose_name='group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='academic.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'timetable entry',
                'verbose_name_plural': 'timetable entries',
                'ordering': ('weekday', 'start_time'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('status', models.CharField(choices=[('held', 'Held'), ('cancelled', 'Cancelled')], default='held', max_length=16, verbose_name='status')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='taken at')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolls_taken', to=settings.AUTH_USER_MODEL, verbose_name='taken by')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academic.timetableslot', verbose_name='timetable entry')),
            ],
            options={
                'verbose_name': 'class session',
                'verbose_name_plural': 'class sessions',
                'ordering': ('-date', 'slot__start_time'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('excused', 'Excused')], db_index=True, default='present', max_length=16, verbose_name='status')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='academic.enrollment', verbose_name='enrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='academic.classsession', verbose_name='class session')),
            ],
            options={
                'verbose_name': 'attendance record',
                'verbose_name_plural': 'attendance records',
                'ordering': ('session__date', 'enrollment__student__last_name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('session', 'enrollment'), name='attendance_unique_per_session_and_enrollment')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='studentgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('program', 'academic_year', 'name'), name='group_unique_name_per_program_and_year'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='timetable_slot_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slot', 'date'), name='class_session_unique_per_slot_and_date'),
        ),
    ]
